# Generated by Django 3.2.9 on 2022-06-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
