# Generated by Django 3.2.9 on 2022-06-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='banner',
            field=models.ImageField(default='polls/images/static/default.jpg', upload_to='polls/images/'),
        ),
    ]
