# Generated by Django 3.2.9 on 2022-06-11 19:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_alter_post_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 11, 19, 56, 53, 326561, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 11, 19, 56, 53, 326561, tzinfo=utc)),
        ),
    ]
